//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Detail
    {
        public Member_Detail()
        {
            this.Sell_BillMember = new HashSet<Sell_BillMember>();
        }
    
        public int MID { get; set; }
        public string Licence { get; set; }
        public string LicenceName { get; set; }
        public string BName { get; set; }
        public string Model { get; set; }
        public string Machine_Number { get; set; }
        public string Color { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string CardID { get; set; }
        public string Adress { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Sell_BillMember> Sell_BillMember { get; set; }
    }
}
